volumes:
  - id: a
    smbPath: //pandora/jav_A
    mountPoint: /Volumes/jav_A
    structureType: conventional
    credentialsKey: pandora.local
    username: patrick_young@hotmail.com

  - id: bg
    smbPath: //pandora/jav_BG
    mountPoint: /Volumes/jav_BG
    structureType: conventional
    credentialsKey: pandora.local
    username: patrick_young@hotmail.com

  - id: hj
    smbPath: //pandora/jav_HJ
    mountPoint: /Volumes/jav_HJ
    structureType: conventional
    credentialsKey: pandora.local
    username: patrick_young@hotmail.com

  - id: k
    smbPath: //pandora/jav_K
    mountPoint: /Volumes/jav_K
    structureType: conventional
    credentialsKey: pandora.local
    username: patrick_young@hotmail.com

  - id: m
    smbPath: //pandora/jav_M
    mountPoint: /Volumes/jav_M
    structureType: conventional
    credentialsKey: pandora.local
    username: patrick_young@hotmail.com

  - id: ma
    smbPath: //pandora/jav_MA
    mountPoint: /Volumes/jav_MA
    structureType: conventional
    credentialsKey: pandora.local
    username: patrick_young@hotmail.com

  - id: n
    smbPath: //pandora/jav_N
    mountPoint: /Volumes/jav_N
    structureType: conventional
    credentialsKey: pandora.local
    username: patrick_young@hotmail.com

  - id: r
    smbPath: //pandora/jav_OR
    mountPoint: /Volumes/jav_OR
    structureType: conventional
    credentialsKey: pandora.local
    username: patrick_young@hotmail.com

  - id: s
    smbPath: //pandora/jav_S
    mountPoint: /Volumes/jav_S
    structureType: conventional
    credentialsKey: pandora.local
    username: patrick_young@hotmail.com

  - id: tz
    smbPath: //pandora/jav_TZ
    mountPoint: /Volumes/jav_TZ
    structureType: conventional
    credentialsKey: pandora.local
    username: patrick_young@hotmail.com

  - id: unsorted
    smbPath: //pandora/jav_unsorted
    mountPoint: /Volumes/jav_unsorted
    structureType: queue
    credentialsKey: pandora.local
    username: patrick_young@hotmail.com

  - id: qnap
    smbPath: //qnap2/jav
    mountPoint: /Volumes/jav
    structureType: conventional
    credentialsKey: QNAP2._smb._tcp.local
    username: pyoung

  - id: classic
    smbPath: //qnap2/JAV/classic
    mountPoint: /Volumes/classic
    structureType: queue
    credentialsKey: QNAP2._smb._tcp.local
    username: pyoung

  - id: collections
    smbPath: //pandora/jav_collections
    mountPoint: /Volumes/jav_collections
    structureType: collections
    credentialsKey: pandora.local
    username: patrick_young@hotmail.com
