package com.organizer3.avstars.model;

import lombok.Builder;
import lombok.Data;

/**
 * Represents one locally-cached screenshot frame for an AV video.
 * Screenshots are generated by {@code av screenshots <actress>} and stored under
 * {@code data/av_screenshots/<videoId>/<seq>.jpg}.
 */
@Data
@Builder
public class AvVideoScreenshot {
    private long id;
    private long avVideoId;
    private int seq;        // 0-based frame index (0–9)
    private String path;    // absolute local filesystem path
}
