package com.organizer3.trash;

import com.organizer3.filesystem.VolumeFileSystem;
import lombok.extern.slf4j.Slf4j;

import java.io.IOException;
import java.nio.file.Path;
import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Service for managing items in a volume's trash folder.
 *
 * <p>All methods are volume-scoped and stateless — callers supply the filesystem and trash root
 * on each call. The sidecar file ({@code <item>.json}) is the sole source of truth for trash state.
 *
 * <p>Listing algorithm:
 * <ol>
 *   <li>Walk {@code trashRoot} recursively to find all {@code .json} files (known sidecars).
 *   <li>For each sidecar, derive the item path (strip {@code .json}) and check existence.
 *       Item exists → valid trashed item. Item missing → orphan sidecar (hidden from listing).
 *   <li>For non-json, non-root paths not already covered by a sidecar: if they are leaf nodes
 *       (file or empty directory), autogenerate a sidecar and include in listing.
 *   <li>Sort all items by sidecar mtime descending. Paginate.
 * </ol>
 *
 * <p>Autogeneration (§4.3.1): a leaf entry without a sidecar had its sidecar write fail after
 * a successful {@code Trash.trashItem} move. Only leaf nodes are candidates — non-empty directories
 * without sidecars are treated as structure directories (mirrors of the original path tree).
 */
@Slf4j
public class TrashService {

    /**
     * Lists trashed items in the given trash root, paginated.
     *
     * @param fs         filesystem for the volume
     * @param volumeId   volume identifier (used in autogenerated sidecars)
     * @param trashRoot  absolute path to the trash folder (e.g., {@code /_trash} or a temp-dir equivalent)
     * @param page       zero-based page index
     * @param pageSize   items per page
     */
    public TrashListing list(VolumeFileSystem fs, String volumeId, Path trashRoot,
                             int page, int pageSize) throws IOException {
        if (!fs.exists(trashRoot)) {
            return new TrashListing(List.of(), 0, page, pageSize);
        }

        List<Path> all = fs.walk(trashRoot);

        // Separate .json (sidecars) from everything else
        List<Path> jsonPaths = all.stream()
                .filter(p -> !p.equals(trashRoot) && p.getFileName().toString().endsWith(".json"))
                .collect(Collectors.toList());
        List<Path> nonJsonPaths = all.stream()
                .filter(p -> !p.equals(trashRoot) && !p.getFileName().toString().endsWith(".json"))
                .collect(Collectors.toList());

        // Map from item path to sidecar path for all valid paired items
        Map<Path, Path> itemToSidecar = new LinkedHashMap<>();
        for (Path json : jsonPaths) {
            Path itemPath = derivedItemPath(json);
            if (fs.exists(itemPath)) {
                itemToSidecar.put(itemPath, json);
            }
            // else: orphan sidecar — hidden per §4.3.2
        }

        // Autogenerate sidecars for leaf orphan items (no sidecar, not content of a claimed item)
        Set<Path> claimedItems = new HashSet<>(itemToSidecar.keySet());
        for (Path p : nonJsonPaths) {
            if (claimedItems.contains(p)) continue;
            if (isContentOfAny(p, claimedItems)) continue;

            // Only autogenerate for leaves: files or empty directories
            boolean isLeaf;
            try {
                isLeaf = !fs.isDirectory(p) || fs.listDirectory(p).isEmpty();
            } catch (IOException e) {
                log.warn("Could not check children of {} for autogeneration: {}", p, e.getMessage());
                continue;
            }
            if (!isLeaf) continue;

            Path sidecarPath = p.getParent().resolve(p.getFileName() + ".json");
            TrashSidecar generated = buildAutogeneratedSidecar(fs, p, trashRoot, volumeId);
            try {
                if (!fs.exists(sidecarPath)) {
                    generated.write(fs, sidecarPath);
                    log.info("Autogenerated trash sidecar for orphan item: {}", p);
                }
                itemToSidecar.put(p, sidecarPath);
            } catch (IOException e) {
                log.warn("Failed to write autogenerated sidecar for {} — using in-memory: {}", p, e.getMessage());
                // Show item in listing with in-memory sidecar; operations other than restore will fail
                itemToSidecar.put(p, sidecarPath); // path is known even if file not written
            }
        }

        // Sort by sidecar mtime descending
        List<Path> sorted = new ArrayList<>(itemToSidecar.keySet());
        sorted.sort(Comparator.comparing(item -> {
            try {
                Instant m = fs.getTimestamps(itemToSidecar.get(item)).modified();
                return m != null ? m : Instant.EPOCH;
            } catch (IOException e) {
                return Instant.EPOCH;
            }
        }, Comparator.reverseOrder()));

        int total = sorted.size();
        int from = Math.min(page * pageSize, total);
        int to = Math.min(from + pageSize, total);
        List<Path> pageItems = sorted.subList(from, to);

        List<TrashItem> items = new ArrayList<>();
        for (Path item : pageItems) {
            Path sidecarPath = itemToSidecar.get(item);
            try {
                TrashSidecar sc = TrashSidecar.read(fs, sidecarPath);
                items.add(new TrashItem(sidecarPath, sc));
            } catch (IOException e) {
                log.warn("Could not read sidecar {} for item {}: {}", sidecarPath, item, e.getMessage());
            }
        }

        return new TrashListing(items, total, page, pageSize);
    }

    /**
     * Schedules items for permanent deletion by setting {@code scheduledDeletionAt = scheduledAt}
     * on each sidecar. Re-scheduling is allowed and resets the clock.
     *
     * @param fs           filesystem for the volume
     * @param sidecarPaths sidecar paths of the items to schedule
     * @param scheduledAt  the scheduled deletion time (typically {@code now + 10 days})
     * @return result with success count and per-item failures
     */
    public BatchResult scheduleForDeletion(VolumeFileSystem fs, List<Path> sidecarPaths,
                                           Instant scheduledAt) {
        int successes = 0;
        List<BatchResult.FailureDetail> failures = new ArrayList<>();
        for (Path sidecarPath : sidecarPaths) {
            try {
                TrashSidecar sc = TrashSidecar.read(fs, sidecarPath);
                sc.withScheduledDeletionAt(scheduledAt).write(fs, sidecarPath);
                successes++;
            } catch (IOException e) {
                failures.add(new BatchResult.FailureDetail(sidecarPath, e.getMessage()));
            }
        }
        return new BatchResult(successes, failures);
    }

    /**
     * Restores trashed items to their original paths.
     *
     * <p>For each sidecar:
     * <ol>
     *   <li>Reads {@code originalPath} from the sidecar.
     *   <li>If {@code originalPath} is already occupied, skips with a failure detail.
     *   <li>Creates missing parent directories.
     *   <li>Moves the item to its original path.
     *   <li>Deletes the sidecar.
     *   <li>Prunes empty ancestor directories inside trash.
     * </ol>
     * The database is not updated — callers should trigger a volume sync after restore.
     *
     * @param fs           filesystem for the volume
     * @param trashRoot    absolute path to the trash folder
     * @param sidecarPaths sidecar paths of the items to restore
     * @return result with success count and per-item failures
     */
    public BatchResult restore(VolumeFileSystem fs, Path trashRoot, List<Path> sidecarPaths) {
        Path volumeRoot = trashRoot.getParent();
        int successes = 0;
        List<BatchResult.FailureDetail> failures = new ArrayList<>();

        for (Path sidecarPath : sidecarPaths) {
            try {
                TrashSidecar sc = TrashSidecar.read(fs, sidecarPath);
                Path itemPath = derivedItemPath(sidecarPath);
                Path originalPath = resolveOriginalPath(volumeRoot, sc.originalPath());

                if (fs.exists(originalPath)) {
                    failures.add(new BatchResult.FailureDetail(sidecarPath,
                            "Skipped — original path already occupied: " + originalPath));
                    continue;
                }

                Path originalParent = originalPath.getParent();
                if (originalParent != null) {
                    fs.createDirectories(originalParent);
                }
                fs.move(itemPath, originalPath);
                fs.delete(sidecarPath);
                pruneEmptyAncestors(fs, trashRoot, itemPath.getParent());
                successes++;
                log.info("Restored trash item: {} -> {}", itemPath, originalPath);
            } catch (IOException e) {
                failures.add(new BatchResult.FailureDetail(sidecarPath, e.getMessage()));
            }
        }
        return new BatchResult(successes, failures);
    }

    /**
     * Sweeps the trash folder and permanently deletes items whose {@code scheduledDeletionAt}
     * is in the past. Also removes orphan sidecars (item already gone).
     *
     * @param fs         filesystem for the volume
     * @param volumeId   volume identifier for the report
     * @param trashRoot  absolute path to the trash folder
     * @param now        current time (used for scheduled-deletion comparison)
     * @return sweep report
     */
    public SweepReport sweepExpired(VolumeFileSystem fs, String volumeId,
                                    Path trashRoot, Instant now) throws IOException {
        if (!fs.exists(trashRoot)) {
            return new SweepReport(volumeId, 0, 0, 0);
        }

        List<Path> all = fs.walk(trashRoot);
        List<Path> jsonPaths = all.stream()
                .filter(p -> !p.equals(trashRoot) && p.getFileName().toString().endsWith(".json"))
                .collect(Collectors.toList());

        int deleted = 0, skipped = 0, errors = 0;

        for (Path sidecarPath : jsonPaths) {
            Path itemPath = derivedItemPath(sidecarPath);

            // Orphan sidecar: item already gone — delete sidecar unconditionally
            if (!fs.exists(itemPath)) {
                try {
                    fs.delete(sidecarPath);
                    pruneEmptyAncestors(fs, trashRoot, sidecarPath.getParent());
                    log.debug("Sweep removed orphan sidecar: {}", sidecarPath);
                    deleted++;
                } catch (IOException e) {
                    log.warn("Sweep failed to remove orphan sidecar {}: {}", sidecarPath, e.getMessage());
                    errors++;
                }
                continue;
            }

            TrashSidecar sc;
            try {
                sc = TrashSidecar.read(fs, sidecarPath);
            } catch (IOException e) {
                log.warn("Sweep could not read sidecar {}: {}", sidecarPath, e.getMessage());
                errors++;
                continue;
            }

            // No schedule or future schedule → skip
            if (sc.scheduledDeletionAt() == null) {
                skipped++;
                continue;
            }
            Instant scheduledAt = Instant.parse(sc.scheduledDeletionAt());
            if (scheduledAt.isAfter(now)) {
                skipped++;
                continue;
            }

            // Delete item first, then sidecar (so sidecar remains if item delete fails)
            try {
                fs.delete(itemPath);
                fs.delete(sidecarPath);
                pruneEmptyAncestors(fs, trashRoot, itemPath.getParent());
                log.info("Sweep permanently deleted: {}", itemPath);
                deleted++;
            } catch (IOException e) {
                // Record failure on sidecar so the UI can surface it
                try {
                    sc.withDeletionFailure(now, e.getMessage()).write(fs, sidecarPath);
                } catch (IOException writeEx) {
                    log.warn("Sweep could not record deletion failure on sidecar {}: {}",
                            sidecarPath, writeEx.getMessage());
                }
                log.warn("Sweep failed to delete {}: {}", itemPath, e.getMessage());
                errors++;
            }
        }

        return new SweepReport(volumeId, deleted, skipped, errors);
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /** Strips {@code .json} from a sidecar path to get its associated item path. */
    private static Path derivedItemPath(Path sidecarPath) {
        String name = sidecarPath.getFileName().toString();
        String itemName = name.substring(0, name.length() - ".json".length());
        return sidecarPath.getParent().resolve(itemName);
    }

    /**
     * Returns the absolute filesystem path for a share-relative {@code originalPath}
     * (e.g., {@code /stars/popular/MIDE-123} → {@code volumeRoot/stars/popular/MIDE-123}).
     */
    private static Path resolveOriginalPath(Path volumeRoot, String originalPath) {
        String relative = originalPath.startsWith("/") ? originalPath.substring(1) : originalPath;
        return relative.isEmpty() ? volumeRoot : volumeRoot.resolve(relative);
    }

    /**
     * Derives the share-relative original path from an item's location inside trash.
     * Strips the {@code trashRoot} prefix and prepends {@code /}.
     */
    static String deriveOriginalPath(Path trashRoot, Path itemPath) {
        String relative = trashRoot.relativize(itemPath).toString();
        return "/" + relative;
    }

    private static boolean isContentOfAny(Path p, Set<Path> claimedItems) {
        for (Path claimed : claimedItems) {
            if (p.startsWith(claimed) && !p.equals(claimed)) return true;
        }
        return false;
    }

    private static TrashSidecar buildAutogeneratedSidecar(VolumeFileSystem fs, Path itemPath,
                                                           Path trashRoot, String volumeId) {
        String originalPath = deriveOriginalPath(trashRoot, itemPath);
        String trashedAt;
        try {
            Instant mtime = fs.getTimestamps(itemPath).modified();
            trashedAt = DateTimeFormatter.ISO_INSTANT.format(mtime != null ? mtime : Instant.now());
        } catch (IOException e) {
            trashedAt = DateTimeFormatter.ISO_INSTANT.format(Instant.now());
        }
        return new TrashSidecar(originalPath, trashedAt, volumeId,
                "Autogenerated — sidecar missing", null, null, null);
    }

    /**
     * Walks up from {@code from} toward (but not including) {@code trashRoot}, deleting empty
     * directories. Stops at the first non-empty directory or {@code trashRoot}.
     */
    private static void pruneEmptyAncestors(VolumeFileSystem fs, Path trashRoot, Path from) {
        Path current = from;
        while (current != null && current.startsWith(trashRoot) && !current.equals(trashRoot)) {
            try {
                List<Path> children = fs.listDirectory(current);
                if (!children.isEmpty()) break;
                fs.delete(current);
                current = current.getParent();
            } catch (IOException e) {
                log.warn("Could not prune empty trash ancestor {}: {}", current, e.getMessage());
                break;
            }
        }
    }
}
