package com.organizer3.sandbox.trash;

import com.organizer3.sandbox.SandboxTestBase;
import com.organizer3.trash.TrashListing;
import com.organizer3.trash.TrashService;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;

import static org.junit.jupiter.api.Assertions.*;

@Tag("sandbox")
class TrashListSandboxTest extends SandboxTestBase {

    private final TrashService svc = new TrashService();

    private SandboxTrashBuilder builder() {
        return new SandboxTrashBuilder(fs, trashRoot(), "vol-a");
    }

    @Test
    void emptyTrashReturnsZero() throws Exception {
        TrashListing result = svc.list(fs, "vol-a", trashRoot(), 0, 50);

        assertEquals(0, result.totalCount());
        assertTrue(result.items().isEmpty());
    }

    @Test
    void listsItemsSortedByMtimeDesc() throws Exception {
        Instant t1 = Instant.parse("2026-04-21T10:00:00Z");
        Instant t2 = Instant.parse("2026-04-22T10:00:00Z");
        Instant t3 = Instant.parse("2026-04-23T10:00:00Z");

        builder().withOriginalPath("/a/ITEM-1").withTrashedAt(t1).build();
        builder().withOriginalPath("/a/ITEM-2").withTrashedAt(t2).build();
        builder().withOriginalPath("/a/ITEM-3").withTrashedAt(t3).build();

        TrashListing result = svc.list(fs, "vol-a", trashRoot(), 0, 50);

        assertEquals(3, result.totalCount());
        // Sorted by sidecar mtime desc — ITEM-3 first (most recent)
        assertEquals("/a/ITEM-3", result.items().get(0).sidecar().originalPath());
        assertEquals("/a/ITEM-2", result.items().get(1).sidecar().originalPath());
        assertEquals("/a/ITEM-1", result.items().get(2).sidecar().originalPath());
    }

    @Test
    void pagination() throws Exception {
        for (int i = 1; i <= 120; i++) {
            Instant t = Instant.parse("2026-04-01T00:00:00Z").plusSeconds(i);
            builder().withOriginalPath("/items/ITEM-" + i).withTrashedAt(t).build();
        }

        TrashListing page0 = svc.list(fs, "vol-a", trashRoot(), 0, 50);
        TrashListing page2 = svc.list(fs, "vol-a", trashRoot(), 2, 50);

        assertEquals(120, page0.totalCount());
        assertEquals(50, page0.items().size());
        assertEquals(120, page2.totalCount());
        assertEquals(20, page2.items().size());
    }

    @Test
    void ignoresNonJsonFiles() throws Exception {
        // A stray .txt file in trash (not an item, not a sidecar)
        Files.createDirectories(trashRoot());
        Path stray = trashRoot().resolve("stray.txt");
        Files.write(stray, new byte[]{0x00});

        // One real item
        builder().withOriginalPath("/items/ITEM-1").build();

        TrashListing result = svc.list(fs, "vol-a", trashRoot(), 0, 50);

        // stray.txt has no sidecar, is a file, so it would autogenerate...
        // but we only count items by their sidecars; stray.txt gets autogenerated as an item
        // The important check: ITEM-1 is present and the .txt is also visible but the .json sidecar is not
        assertTrue(result.items().stream().noneMatch(i -> i.sidecar().originalPath().endsWith(".json")),
                "Sidecar files must never appear as items in the listing");
    }

    @Test
    void autogeneratesMissingSidecar() throws Exception {
        // Create an item folder WITHOUT a sidecar (simulates failed sidecar write)
        builder().withOriginalPath("/stars/foo/MIDE-1").asFolder().withoutSidecar().build();

        TrashListing result = svc.list(fs, "vol-a", trashRoot(), 0, 50);

        assertEquals(1, result.totalCount());
        assertEquals("/stars/foo/MIDE-1", result.items().get(0).sidecar().originalPath());
        assertEquals("Autogenerated — sidecar missing", result.items().get(0).sidecar().reason());

        // Verify sidecar was actually written to disk
        Path expectedSidecar = trashRoot().resolve("stars/foo/MIDE-1.json");
        assertTrue(Files.exists(expectedSidecar), "Autogenerated sidecar must be written to disk");
    }

    @Test
    void autogenerationIsIdempotent() throws Exception {
        builder().withOriginalPath("/stars/foo/MIDE-1").asFolder().withoutSidecar().build();

        // First listing — autogenerates sidecar
        svc.list(fs, "vol-a", trashRoot(), 0, 50);

        Path sidecarPath = trashRoot().resolve("stars/foo/MIDE-1.json");
        long mtimeAfterFirst = Files.getLastModifiedTime(sidecarPath).toMillis();

        // Second listing — must not overwrite
        svc.list(fs, "vol-a", trashRoot(), 0, 50);
        long mtimeAfterSecond = Files.getLastModifiedTime(sidecarPath).toMillis();

        assertEquals(mtimeAfterFirst, mtimeAfterSecond, "Second listing must not overwrite the autogenerated sidecar");
    }

    @Test
    void orphanSidecarHiddenFromListing() throws Exception {
        // Create a sidecar whose item no longer exists
        Files.createDirectories(trashRoot().resolve("a"));
        Path orphanSidecar = trashRoot().resolve("a/foo.json");
        new com.organizer3.trash.TrashSidecar("/a/foo", "2026-04-23T10:00:00Z", "vol-a", "test",
                null, null, null).write(fs, orphanSidecar);
        // No /a/foo item exists

        TrashListing result = svc.list(fs, "vol-a", trashRoot(), 0, 50);

        assertEquals(0, result.totalCount(), "Orphan sidecar must be hidden from listing");
        assertTrue(result.items().isEmpty());
    }
}
